DROP TABLE IF EXISTS user_friends CASCADE;

CREATE TABLE user_friends (
    id SERIAL PRIMARY KEY NOT NULL,

    user_id_1 INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_id_2 INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);